
let boxes =document.querySelectorAll(".box");
let resetbtn = document.querySelector("#reset-btn");
let newGameBtn = document.querySelector("#New");
let msgCintainer = document.querySelector(".msg-Contaner");
let msg = document.querySelector("#msg");



let turn0 = true; // playex, playe0, 

const winpatterns = [
    [0,1,2],
    [0,3,4],
    [0,4,8],
    [1,4,7],
    [2,5,8],
    [2,4,6],
    [3,4,5],
    [6,7,8],
];
boxes.forEach((box) =>{
    box.addEventListener("click", () =>{
        console.log("box was clicked ");
       if(turn0){
        box.innerText ="O";
        turn0 = false;

       }else{
        box.innerText = "X";
        turn0 =true;
       }
       box.disabled = true;

       checkwinner ();
    });
});
const showWinner = (winner) =>{
    msg.innerText =`Congratultions, Winner is ${winner}`;
    msgContainer.classList.remove("hide");
}
const checkwinner = () =>{
    for(let pattern of winpatterns){
       
    let pos1Val = boxes [pattern[0]].innerText;
    let pos2Val = boxes [pattern[0]].innerText;
    let pos3Val = boxes [pattern[0]].innerText;

    if (pos1Val != "" && pos2Val !="" && pos3Val != ""){
         if(pos1Val === pos2Val && pos2Val === pos3Val){
            console.log("winner",pos1Val );
            showWinner(pos1Val);
      }
    }
  }
};






